CREATE DATABASE customers;

CREATE TABLE customer (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
 first_name VARCHAR(255) NOT NULL,
 last_name VARCHAR(255) NOT NULL,
 birth_date DATE NOT NULL,
 mobile VARCHAR(10) NOT NULL,
 address1 VARCHAR(255) NOT NULL,
 address2 VARCHAR(255) ,
 gender ENUM('MALE','FEMALE') NOT NULL,
 email VARCHAR(255) NOT NULL
);
